# syntax=docker/dockerfile:1
FROM ubuntu:18.04
CMD echo "This is a test"
CMD apt-get update
CMD apt-get install linux-generic -y
CMD apt-get install wget -y
CMD apt-get install systemd -y
CMD wget http://download.ni.com/ni-linux-desktop/2020.07/ni-software-2020-bionic_20.1.0.49152-0+f0_all.deb
CMD apt install ./ni-software-2020-bionic_20.1.0.49152-0+f0_all.deb -y
CMD apt update
CMD kernel_release="$(uname -r | cut --complement -d'.' -f3)"
CMD kernel_release_versions="$(apt-cache search linux-image-${kernel_release})"
CMD kernel_release_versions_generic="$(grep linux-image-"${kernel_release_version}".*-generic <<< CMD "$kernel_release_versions")"
CMD newest_kernel_of_release="$(echo "$kernel_release_versions_generic" | tail -n1 | cut -d' ' -f1 )"
CMD apt-get install $newest_kernel_of_release
CMD newest_kernel_of_release_headers=${newest_kernel_of_release/image/headers}
CMD apt-get install $newest_kernel_of_release_headers
CMD apt-get update
CMD apt install ni-daqmx -y
CMD dkms autoinstall


Robert Des Rosier

